services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    restart: unless-stopped
    user: "1000:1000"
    command: ["python", "app.py"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 